[package]
name = "zk_implementations"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.5.0"
ark-std = "0.5.0"
ff = "0.13"
rand = "0.9"
sha3 = "0.10" 
ark-poly = "0.5" 
ark-bn254 = "0.5"
